# Generated by Django 3.0.5 on 2023-06-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='The Daily Blog', max_length=255),
        ),
    ]
